Repository stratosphereips/AIVPN, pull requests merged in 2022-11, with the labels that each got.

#27 Small improvements to Contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#29 Bugfix Slips IDS process hangs
  docker-compose_EXAMPLE.yml
  mod_slips/Dockerfile
  mod_slips/mod_slips.py
  mod_slips/slips_configuration.conf
  mod_slips/slips_slack_bot_token_secret
  mod_slips/slips_whitelist.conf
Labels: bug

#28 aivpn.py refactoring
  aivpn.py
Labels: refactor

#30 Refactor mod slips
  mod_slips/Dockerfile
  mod_slips/mod_slips.py
  mod_slips/requirements.txt
  mod_slips/slips_configuration.conf
Labels: enhancement, refactor

#32 Refactor mod comm recv
  mod_comm_recv/mod_comm_recv.py
Labels: refactor
